config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        welcome#index
#          new_user_profile GET    /users/:user_id/profile/new(.:format)                                                    user_profile#new
#         edit_user_profile GET    /users/:user_id/profile/edit(.:format)                                                   user_profile#edit
#              user_profile GET    /users/:user_id/profile(.:format)                                                        user_profile#show
#                           PATCH  /users/:user_id/profile(.:format)                                                        user_profile#update
#                           PUT    /users/:user_id/profile(.:format)                                                        user_profile#update
#                           DELETE /users/:user_id/profile(.:format)                                                        user_profile#destroy
#                           POST   /users/:user_id/profile(.:format)                                                        user_profile#create
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#                     blogs GET    /blogs(.:format)                                                                         blogs#index
#                           POST   /blogs(.:format)                                                                         blogs#create
#                  new_blog GET    /blogs/new(.:format)                                                                     blogs#new
#                 edit_blog GET    /blogs/:id/edit(.:format)                                                                blogs#edit
#                      blog GET    /blogs/:id(.:format)                                                                     blogs#show
#                           PATCH  /blogs/:id(.:format)                                                                     blogs#update
#                           PUT    /blogs/:id(.:format)                                                                     blogs#update
#                           DELETE /blogs/:id(.:format)                                                                     blogs#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :users do
    resource :profile,:controller => "user_profile"
  end

  resources :blogs do
    member do
      post :add_tag
      post :delete_tag
    end
  end

  resources :tags
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :bigint           not null, primary key
#  user_id    :integer
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blog < ApplicationRecord
  belongs_to :user
  has_many :blog_tags
  has_many :tags, :through => :blog_tags
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout 'application'
  def index
    @blogs = Blog.where(is_publish: true)
    tag_id = params[:tag_id]
    if tag_id.present?
      @blogs = @blogs.joins(:blog_tags).where('blog_tags.tag_id = ?', tag_id.to_i)
    end
  end

  def new
    @blog = Blog.new()
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def show
    @blog = Blog.find_by(id: params[:id])
  end

  def edit
    @tags = Tag.all
    @blog = Blog.find_by(id: params[:id])
  end

  def update
    @blog = Blog.find_by(id: params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find_by(id: params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "已删除"
  end

  def add_tag
    # redirect_to blogs_path, notice: "已删除"
    blog = Blog.find_by(id: params[:id])
    tag_id = params[:format]
    existed_tags = blog.tags.ids
    if existed_tags.include?(tag_id.to_i)
      flash.now[:notice]="已添加"
    else
      BlogTag.create(blog_id: params[:id], tag_id: params[:format])
      redirect_to blog_path(blog)
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:content, :user_id, :title)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.slim
.blog-form
  = simple_form_for blog do |f|
    - if @tags.present?
      - @tags.each do |tag|
        span.label.blog-form-label class="#{ blog.tags.ids.include?(tag.id.to_i) ? "label-success" : 'label-primary'}"
          = link_to tag.name, add_tag_blog_path(blog,tag.id), method: :post
    = f.hidden_field :user_id, value: current_user.id
    = f.input :title, as: :string,label: '标题', required: true
    = f.input :content, as: :text, label: '内容', required: true, input_html: { class: "blog-form-content" }
    = f.submit '确定发布', class: "btn btn-primary"

app/views/blogs/edit.html.slim
.blog-edit-page
  = render 'form', blog: @blog, tags: @tags

app/views/blogs/index.html.erb
<div class="blog-index-page">
  <% if @blogs.present? %>
    <% @blogs.each do |blog|%>
      <%= link_to blog_path(blog) do %>
        <div class="panel panel-success animate__animated animate__fadeInBottomRight">
          <div class="panel-heading">
            <%= blog.title %>
          </div>
          <div class="panel-body">
            <div class="panel-body-content">
              <div class="panel-body-content-left">
                <% if blog.tags.present? %>
                  <% blog.tags.each do |tag| %>
                    <span class="label label-success"><%= tag.name %></span>
                  <% end %>
                <% end %>
              </div>
              <div class="panel-body-content-right">
                发布时间<%= blog.created_at.strftime('%F %T') %>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    <%end%>
  <%end%>
</div>

app/views/blogs/index.html.slim
.blog-index-page
  - if @blogs.present?
    table.table
      thead.thead-dark
        tr
          th 文章
          th 时间
          th 创建人
          th 操作
      tbody
        - @blogs.each do |blog|
          tr
            td = blog.title
            td = blog.created_at.strftime('%F %T')
            td = blog.user.profile.name
            td
              = link_to '查看', blog_path(blog), class: "btn btn-xs btn-primary"
              = link_to '编辑', edit_blog_path(blog), class: "btn btn-xs btn-info"
              = link_to '删除', blog_path(blog), method: :delete, class: "btn btn-xs btn-warning"

  - else
    | 暂无文章
  .blog-actions
    = link_to '发布文章', new_blog_path, class: "btn btn-primary"

app/views/blogs/new.html.slim
.blog-new-page
  = render 'form', blog: @blog

app/views/blogs/show.html.slim
.blog-show-page
  .section.blog-title
    = @blog.title
  - if @blog.tags.present?
    .section.blog-tag
      - @blog.tags.each do |tag|
        span.label.label-success
          = tag.name

  .section.blog-content
    = markdown(@blog.content)
- if current_user && current_user.is_admin
  = link_to '编辑',edit_blog_path(@blog), class: "btn btn-info"